endpoints:
  - name: openai
    endpoint_url: "https://api.openai.com/v1"
    api_key_env: "OPENAI_API_KEY"
    model: "gpt-4"
    context_window_size: 8192
    chunk_size: 4096
  - name: local_mistral
    endpoint_url: "http://localhost:8080"
    api_key_env: "LOCAL_API_KEY"
    model: "mistral"
    context_window_size: 100
    chunk_size: 100